services:
  - type: web
    name: bot-qnpc-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app-web-qnpc-fn:app
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7862312312:AAGRe-kNQPtz2CDmfowFlCAPmJbYUIcJKvg
