services:
  - type: web
    name: bot-qnpc
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot-qnpc:app
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7862312312:AAGRe-kNQPtz2CDmfowFlCAPmJbYUIcJKvg
